### ISSUE TITLE
Publically available feeds

### ISSUE THREAD

**Issue by T145** [CyberSaiyanIT/InfoSharing#42]
I've been using https://infosharing.cybersaiyan.it/feeds/CS-PIHOLE, which turns out to now be empty.

This was in one of your scripts: https://infosharing.cybersaiyan.it/feeds/CS-COMMUNITY-HTTP?v=csv&f=type&f=indicator&tr=1

But based on the context seems like a spot where files are submitted. Are there any public feeds still available?

**Comment by CyberSaiyanIT** [comment]
Tks for reporting
As you can see here https://infosharing.cybersaiyan.it/feeds/CS-COMMUNITY-HTTP feeds are still available but the pi.hole feed just take domains (not full urls).
There is a need to estract the domain part from the full url so CS-PIHOLE feed will be filled again, will work on a fix to this asap.
Tks for reporting

**Comment by T145** [comment]
Any estimated time to completion? I just don't want to forget to un-deprecate this source in my blocklist.

**Comment by T145** [comment]
Seems to be back up!
